import { defineConfig } from 'vitepress'

export default defineConfig({
  base: '/cursor-reverse-engineering/',
  title: '好久之前对Cursor的逆向，基于0.48.8版本',
  description: '好久之前对Cursor的逆向，基于0.48.8版本',
  lang: 'zh-CN',
  lastUpdated: true,
  ignoreDeadLinks: true,
  markdown: {
    lineNumbers: true,
  },
  themeConfig: {
    search: {
      provider: 'local',
    },
    nav: [
      { text: '文档首页', link: '/' },
      { text: 'GitHub', link: 'https://github.com/vibe-coding-labs/cursor-reverse-engineering' },
    ],
    sidebar: [
          { text: "好久之前对Cursor的逆向，基于0.48.8版本", items: [
            { text: "首页", link: "/" },
            { text: "Cursor 3.7.27 product.json 深度分析", link: "/01-configuration/product-json-analysis" },
            { text: "Cursor 3.7.27 main.js 主进程逆向分析", link: "/02-main-process/main-js-analysis" },
            { text: "workbench.desktop.main.js 深度架构分析", link: "/02-main-process/workbench-deep-architecture" },
            { text: "Cursor Agent 执行系统分析 (cursor-agent-exec)", link: "/03-agent-system/cursor-agent-exec-analysis" },
            { text: "Cursor MCP 协议实现分析 (cursor-mcp)", link: "/04-mcp-protocol/cursor-mcp-analysis" },
            { text: "Cursor MCP 传输层架构分析", link: "/04-mcp-protocol/mcp-transport-analysis" },
            { text: "Cursor AI 通信协议 — 完整逆向分析", link: "/05-communication-protocol/ai-communication-protocol" },
            { text: "Cursor AI 通信协议 — 最终确定性报告", link: "/05-communication-protocol/final-communication-protocol" },
            { text: "Cursor 检索 (Retrieval) 分析索引", link: "/05-retrieval/README" },
            { text: "Cursor Tunnel 通信机制分析", link: "/06-communication/cursor-tunnel-analysis" },
            { text: "Cursor 3.7.27 登录协议 — 最终报告", link: "/07-authentication/FINAL_REPORT" },
            { text: "Cursor 3.7.27 认证授权流程 — 完整逆向分析", link: "/07-authentication/auth-flow-analysis" },
            { text: "Cursor 3.7.27 授权登录流程 — Python 模拟指南", link: "/07-authentication/auth-login-python-simulation" },
            { text: "Cursor 扩展批量分析 (未覆盖的13个扩展)", link: "/08-extensions/extensions-batch-analysis" },
            { text: "Cursor 3.7.27 Node Modules 深度分析", link: "/09-node-modules/node-modules-analysis" },
            { text: "Glass UI 品牌资源分析", link: "/10-glass-ui/glass-ui-analysis" },
            { text: "Cursor 3.7.27 逆向分析 — 综合架构总结", link: "/11-summary/architecture-summary" },
            { text: "Cursor 免费版（Free Tier）能力与限制调研报告", link: "/12-free-tier/free-tier-report" },
            { text: "Cursor 风控/指纹/遥测 — 完整参考手册", link: "/13-anti-fingerprint/COMPLETE_REFERENCE" },
            { text: "Cursor 逆向分析索引 — 完整目录", link: "/13-anti-fingerprint/INDEX" },
            { text: "Cursor 风控/指纹/遥测 — 完整分析目录", link: "/13-anti-fingerprint/README" },
            { text: "Cursor 风控、设备指纹与遥测机制分析 (第1轮)", link: "/13-anti-fingerprint/round-1-anti-fingerprint" },
            { text: "Cursor 风控体系 — 完整错误码与风控触发条件 (第10轮)", link: "/13-anti-fingerprint/round-10-error-codes" },
            { text: "Cursor 风控体系 — 运行时风控实现 (第11轮)", link: "/13-anti-fingerprint/round-11-rate-limiting" },
            { text: "Cursor 风控体系 — 重试、退避与超时策略 (第12轮)", link: "/13-anti-fingerprint/round-12-retry-backoff" },
            { text: "Cursor 风控体系 — 安全策略与访问控制 (第13轮)", link: "/13-anti-fingerprint/round-13-security-policy" },
            { text: "Cursor 风控体系 — 隐私模式、加密存储与代理认证 (第14轮)", link: "/13-anti-fingerprint/round-14-privacy-encryption" },
            { text: "Cursor 风控体系 — Statsig 初始化、URL 配置、Sentry 上下文 (第15轮)", link: "/13-anti-fingerprint/round-15-statsig-init" },
            { text: "Cursor 风控体系 — 请求追踪、重连与指标 (第16轮)", link: "/13-anti-fingerprint/round-16-reconnect-metrics" },
            { text: "Cursor 风控体系 — 模型路由、并行调用与配置 (第17轮)", link: "/13-anti-fingerprint/round-17-model-routing" },
            { text: "Cursor 风控体系 — 模拟客户端实操手册 (第18轮)", link: "/13-anti-fingerprint/round-18-practical-guide" },
            { text: "Cursor 风控体系 — 用量限制与计费 (第19轮)", link: "/13-anti-fingerprint/round-19-hard-limit" },
            { text: "Cursor 风控、设备指纹与遥测机制分析 (第2轮)", link: "/13-anti-fingerprint/round-2-anti-fingerprint" },
            { text: "Cursor 风控体系 — 用量展示、光标 KV 存储、API 提案 (第20轮)", link: "/13-anti-fingerprint/round-20-usage-display" },
            { text: "Cursor 风控体系 — 进程列表 (Proclist) 采集 (第21轮)", link: "/13-anti-fingerprint/round-21-proclist" },
            { text: "Cursor 逆向分析 — 跨维度关联总览 (第28轮)", link: "/13-anti-fingerprint/round-28-cross-dimension" },
            { text: "Cursor 逆向分析 — 全量覆盖证明 (第29轮)", link: "/13-anti-fingerprint/round-29-completion-proof" },
            { text: "Cursor 风控、设备指纹与遥测机制分析 (第3轮 — 最终汇总)", link: "/13-anti-fingerprint/round-3-summary" },
            { text: "Cursor 主进程 ⇄ 扩展进程 IPC 协议 (第33轮)", link: "/13-anti-fingerprint/round-33-ipc-protocol" },
            { text: "Cursor IPC 服务 — 方法签名提取 (第34轮)", link: "/13-anti-fingerprint/round-34-ipc-methods" },
            { text: "Cursor telemetry — commonProperties 完整清单 (第35轮)", link: "/13-anti-fingerprint/round-35-common-props" },
            { text: "Cursor 逆向 — 最终证明 (第36轮)", link: "/13-anti-fingerprint/round-36-final-proof" },
            { text: "Cursor 风控、设备指纹与遥测机制分析 (第4轮)", link: "/13-anti-fingerprint/round-4-comprehensive" },
            { text: "Cursor 风控、设备指纹与遥测机制分析 (第5轮)", link: "/13-anti-fingerprint/round-5-deep-dive" },
            { text: "Cursor 风控、设备指纹与遥测机制分析 (第6轮)", link: "/13-anti-fingerprint/round-6-machineid-source" },
            { text: "Cursor 风控、设备指纹与遥测机制分析 (第7轮)", link: "/13-anti-fingerprint/round-7-runtime-headers" },
            { text: "Cursor 风控、设备指纹与遥测机制分析 (第8轮)", link: "/13-anti-fingerprint/round-8-machineid-fix" },
            { text: "Cursor 风控、设备指纹与遥测机制分析 (第9轮 — 终章)", link: "/13-anti-fingerprint/round-9-final" },
            { text: "Cursor 协议分析索引", link: "/14-agent-protocols/README" },
            { text: "cursor-browser-automation 协议分析", link: "/14-agent-protocols/browser-automation-protocol" },
            { text: "cursor-commits Git 集成协议分析", link: "/14-agent-protocols/commits-protocol" },
            { text: "Protobuf Schema 参考手册", link: "/14-agent-protocols/protobuf-schema-reference" },
            { text: "cursor-retrieval 检索协议分析", link: "/14-agent-protocols/retrieval-protocol" },
            { text: "Cursor Agent Tool Calling 协议分析", link: "/14-agent-protocols/tool-calling-protocol" },
            { text: "Cursor 核心进程文件分析", link: "/15-core-files/core-files-analysis" },
            { text: "Cursor 逆向分析 — 第八轮报告：cursor-sandbox Rust 沙箱系统", link: "/15-core-files/cursor-sandbox-analysis" },
            { text: "Cursor 协议修正与深度分析报告 (Round 1)", link: "/16-protocol-correction/protocol-discovery-report" },
            { text: "Cursor 逆向分析 — 第二轮深度分析报告", link: "/16-protocol-correction/round-2-deep-analysis" },
            { text: "Cursor 逆向分析 — 第三轮深度分析报告", link: "/16-protocol-correction/round-3-protocol-duality-and-statsig" },
            { text: "Cursor 逆向分析 — 第四轮报告：ChatService 协议突破与风控验证", link: "/16-protocol-correction/round-4-chatservice-blocked" },
            { text: "Cursor 逆向分析 — 第五轮报告：检索 RPC 协议与 77 种工具类型", link: "/16-protocol-correction/round-5-retrieval-rpc-77-tools" },
            { text: "Cursor 逆向分析 — 第六轮报告：Hook 系统与 12 种 AI 模式", link: "/16-protocol-correction/round-6-hooks-and-final-summary" },
            { text: "Cursor 逆向分析 — 第七轮报告：@anysphere/file-service Rust 原生模块", link: "/16-protocol-correction/round-7-file-service-native-module" },
            { text: "Cursor 3.7.27 → 3.9.16 版本差异逆向分析报告", link: "/17-version-diff/version-3.7-to-3.9-diff-report" },
            { text: "Cursor 3.7.27 → 3.9.16 版本差异逆向分析报告（增强版）", link: "/17-version-diff/version-3.7-to-3.9-enhance-diff-report" },
            { text: "Cursor 3.7.27 逆向分析报告", link: "/README" },
          ] }
        ],
    socialLinks: [
      { icon: 'github', link: 'https://github.com/vibe-coding-labs/cursor-reverse-engineering' },
    ],
    footer: {
      message: '基于 VitePress 构建',
    },
  },
})
